"""Add ai_suggestions and modified_content fields to Resume model

Revision ID: 7cd695fa92f5
Revises: 9875f41956ad
Create Date: 2025-05-23 21:44:54.526798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd695fa92f5'
down_revision = '9875f41956ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_suggestions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('modified_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('modified_content')
        batch_op.drop_column('ai_suggestions')

    # ### end Alembic commands ###
